#ifndef _EXPAND_H_
#define _EXPAND_H_

#define EXPAND_1(...) __VA_ARGS__

#define EXPAND_E0(...) __VA_ARGS__
#define EXPAND_E1(...) EXPAND_E0(EXPAND_E0(EXPAND_E0(EXPAND_E0(__VA_ARGS__))))
#define EXPAND_E2(...) EXPAND_E1(EXPAND_E1(EXPAND_E1(EXPAND_E1(__VA_ARGS__))))
#define EXPAND_E3(...) EXPAND_E2(EXPAND_E2(EXPAND_E2(EXPAND_E2(__VA_ARGS__))))
#define EXPAND_E4(...) EXPAND_E3(EXPAND_E3(EXPAND_E3(EXPAND_E3(__VA_ARGS__))))
#define EXPAND_E5(...) EXPAND_E4(EXPAND_E4(EXPAND_E4(EXPAND_E4(__VA_ARGS__))))
#define EXPAND_E6(...) EXPAND_E5(EXPAND_E5(EXPAND_E5(EXPAND_E5(__VA_ARGS__))))
#define EXPAND_E7(...) EXPAND_E6(EXPAND_E6(EXPAND_E6(EXPAND_E6(__VA_ARGS__))))
#define EXPAND_E8(...) EXPAND_E7(EXPAND_E7(EXPAND_E7(EXPAND_E7(__VA_ARGS__))))
#define EXPAND_E9(...) EXPAND_E8(EXPAND_E8(EXPAND_E8(EXPAND_E8(__VA_ARGS__))))

#define EXPAND(...) EXPAND_E4(__VA_ARGS__)

#endif
